export const CITIZENSHIP_COUNTRIES = [
    { gr: 'Άγιος Βικέντιος και Γρεναδίνες', en: 'Saint Vincent and the Grenadines' },
    { gr: 'Άγιος Μαρίνος', en: 'San Marino' },
    { gr: 'Άγιος Χριστόφορος και Νέβις', en: 'Saint Kitts and Nevis' },
    { gr: 'Αίγυπτος', en: 'Egypt' },
    { gr: 'Αγία Λουκία', en: 'Saint Lucia' },
    { gr: 'Αζερμπαϊτζάν', en: 'Azerbaijan' },
    { gr: 'Αιθιοπία', en: 'Ethiopia' },
    { gr: 'Ακτή Ελεφαντοστού', en: 'Côte d\'Ivoire' },
    { gr: 'Αλβανία', en: 'Albania' },
    { gr: 'Αλγερία', en: 'Algeria' },
    { gr: 'Ανατολικό Τιμόρ', en: 'Timor-Leste' },
    { gr: 'Ανγκόλα', en: 'Angola' },
    { gr: 'Ανδόρρα', en: 'Andorra' },
    { gr: 'Αντίγκουα και Μπαρμπούντα', en: 'Antigua and Barbuda' },
    { gr: 'Αργεντινή', en: 'Argentina' },
    { gr: 'Αρμενία', en: 'Armenia' },
    { gr: 'Αυστρία', en: 'Austria' },
    { gr: 'Αυστραλία', en: 'Australia' },
    { gr: 'Αφγανιστάν', en: 'Afghanistan' },
    { gr: 'Αϊτή', en: 'Haiti' },
    { gr: 'Βέλγιο', en: 'Belgium' },
    { gr: 'Βανουάτου', en: 'Vanuatu' },
    { gr: 'Βενεζουέλα', en: 'Venezuela' },
    { gr: 'Βιετνάμ', en: 'Viet Nam' },
    { gr: 'Βολιβία', en: 'Bolivia' },
    { gr: 'Βοσνία και Ερζεγοβίνη', en: 'Bosnia and Herzegovina' },
    { gr: 'Βουλγαρία', en: 'Bulgaria' },
    { gr: 'Βραζιλία', en: 'Brazil' },
    { gr: 'Βόρεια Κορέα', en: 'Democratic People\'s Republic of Korea' },
    { gr: 'Γαλλία', en: 'France' },
    { gr: 'Γερμανία', en: 'Germany' },
    { gr: 'Γεωργία', en: 'Georgia' },
    { gr: 'Γκάμπια', en: 'Gambia' },
    { gr: 'Γκάνα', en: 'Ghana' },
    { gr: 'Γκαμπόν', en: 'Gabon' },
    { gr: 'Γουατεμάλα', en: 'Guatemala' },
    { gr: 'Γουιάνα', en: 'Guyana' },
    { gr: 'Γουινέα', en: 'Guinea' },
    { gr: 'Γουινέα-Μπισσάου', en: 'Guinea-Bissau' },
    { gr: 'Γρενάδα', en: 'Grenada' },
    { gr: 'Δανία', en: 'Denmark' },
    { gr: 'Δημοκρατία της Μακεδονίας (ΠΓΔΜ)', en: 'North Macedonia' },
    { gr: 'Δημοκρατία του Κονγκό', en: 'Congo' },
    { gr: 'Δομινίκα', en: 'Dominica' },
    { gr: 'Δομινικανή Δημοκρατία', en: 'Dominican Republic' },
    { gr: 'Ελ Σαλβαδόρ', en: 'El Salvador' },
    { gr: 'Ελβετία', en: 'Switzerland' },
    { gr: 'Ελλάδα', en: 'Greece' },
    { gr: 'Ερυθραία', en: 'Eritrea' },
    { gr: 'Εσθονία', en: 'Estonia' },
    { gr: 'Ζάμπια', en: 'Zambia' },
    { gr: 'Ζιμπάμπουε', en: 'Zimbabwe' },
    { gr: 'Ηνωμένα Αραβικά Εμιράτα', en: 'United Arab Emirates' },
    { gr: 'Ηνωμένες Πολιτείες Αμερικής', en: 'United States of America' },
    { gr: 'Ηνωμένο Βασίλειο', en: 'United Kingdom' },
    { gr: 'Ιαπωνία', en: 'Japan' },
    { gr: 'Ινδία', en: 'India' },
    { gr: 'Ινδονησία', en: 'Indonesia' },
    { gr: 'Ιορδανία', en: 'Jordan' },
    { gr: 'Ιράκ', en: 'Iraq' },
    { gr: 'Ιράν', en: 'Iran' },
    { gr: 'Ιρλανδία', en: 'Ireland' },
    { gr: 'Ισημερινή Γουινέα', en: 'Equatorial Guinea' },
    { gr: 'Ισημερινός', en: 'Ecuador' },
    { gr: 'Ισλανδία', en: 'Iceland' },
    { gr: 'Ισπανία', en: 'Spain' },
    { gr: 'Ισραήλ', en: 'Israel' },
    { gr: 'Ιταλία', en: 'Italy' },
    { gr: 'Κένυα', en: 'Kenya' },
    { gr: 'Κίνα', en: 'China' },
    { gr: 'Καζακστάν', en: 'Kazakhstan' },
    { gr: 'Καμερούν', en: 'Cameroon' },
    { gr: 'Καμπότζη', en: 'Cambodia' },
    { gr: 'Καναδάς', en: 'Canada' },
    { gr: 'Κατάρ', en: 'Qatar' },
    { gr: 'Κεντροαφρικανική Δημοκρατία', en: 'Central African Republic' },
    { gr: 'Κιργιζία', en: 'Kyrgyzstan' },
    { gr: 'Κιριμπάτι', en: 'Kiribati' },
    { gr: 'Κολομβία', en: 'Colombia' },
    { gr: 'Κομόρες', en: 'Comoros' },
    { gr: 'Κουβέιτ', en: 'Kuwait' },
    { gr: 'Κούβα', en: 'Cuba' },
    { gr: 'Κράτος της Παλαιστίνης', en: 'Palestine, State of' },
    { gr: 'Κροατία', en: 'Croatia' },
    { gr: 'Κόσοβο', en: 'Kosovo' },
    { gr: 'Κόστα Ρίκα', en: 'Costa Rica' },
    { gr: 'Κύπρος', en: 'Cyprus' },
    { gr: 'Λάος', en: 'Laos' },
    { gr: 'Λίβανος', en: 'Lebanon' },
    { gr: 'Λίχτενσταϊν', en: 'Liechtenstein' },
    { gr: 'Λαϊκή Δημοκρατία του Κονγκό', en: 'Democratic Republic of the Congo' },
    { gr: 'Λεσότο', en: 'Lesotho' },
    { gr: 'Λετονία', en: 'Latvia' },
    { gr: 'Λευκορωσία', en: 'Belarus' },
    { gr: 'Λιβερία', en: 'Liberia' },
    { gr: 'Λιβύη', en: 'Libya' },
    { gr: 'Λιθουανία', en: 'Lithuania' },
    { gr: 'Λουξεμβούργο', en: 'Luxembourg' },
    { gr: 'Μάλι', en: 'Mali' },
    { gr: 'Μάλτα', en: 'Malta' },
    { gr: 'Μαδαγασκάρη', en: 'Madagascar' },
    { gr: 'Μαλάουι', en: 'Malawi' },
    { gr: 'Μαλαισία', en: 'Malaysia' },
    { gr: 'Μαλδίβες', en: 'Maldives' },
    { gr: 'Μαρόκο', en: 'Morocco' },
    { gr: 'Μαυρίκιος', en: 'Mauritius' },
    { gr: 'Μαυριτανία', en: 'Mauritania' },
    { gr: 'Μαυροβούνιο', en: 'Montenegro' },
    { gr: 'Μεξικό', en: 'Mexico' },
    { gr: 'Μιανμάρ', en: 'Myanmar' },
    { gr: 'Μικρονησία', en: 'Micronesia (Federated States of)' },
    { gr: 'Μογγολία', en: 'Mongolia' },
    { gr: 'Μοζαμβίκη', en: 'Mozambique' },
    { gr: 'Μολδαβία', en: 'Moldova' },
    { gr: 'Μονακό', en: 'Monaco' },
    { gr: 'Μπανγκλαντές', en: 'Bangladesh' },
    { gr: 'Μπαρμπάντος', en: 'Barbados' },
    { gr: 'Μπαχάμες', en: 'Bahamas' },
    { gr: 'Μπαχρέιν', en: 'Bahrain' },
    { gr: 'Μπελίζ', en: 'Belize' },
    { gr: 'Μπενίν', en: 'Benin' },
    { gr: 'Μποτσουάνα', en: 'Botswana' },
    { gr: 'Μπουρκίνα Φάσο', en: 'Burkina Faso' },
    { gr: 'Μπουρούντι', en: 'Burundi' },
    { gr: 'Μπουτάν', en: 'Bhutan' },
    { gr: 'Μπρουνέι', en: 'Brunei Darussalam' },
    { gr: 'Νέα Ζηλανδία', en: 'New Zealand' },
    { gr: 'Νήσοι Μάρσαλ', en: 'Marshall Islands' },
    { gr: 'Νήσοι Σολομώντα', en: 'Solomon Islands' },
    { gr: 'Νίγηρας', en: 'Niger' },
    { gr: 'Ναμίμπια', en: 'Namibia' },
    { gr: 'Ναούρου', en: 'Nauru' },
    { gr: 'Νεπάλ', en: 'Nepal' },
    { gr: 'Νιγηρία', en: 'Nigeria' },
    { gr: 'Νικαράγουα', en: 'Nicaragua' },
    { gr: 'Νορβηγία', en: 'Norway' },
    { gr: 'Νότια Αφρική', en: 'South Africa' },
    { gr: 'Νότια Κορέα', en: 'Republic of Korea' },
    { gr: 'Νότιο Σουδάν', en: 'South Sudan' },
    { gr: 'Ολλανδία', en: 'Netherlands' },
    { gr: 'Ομάν', en: 'Oman' },
    { gr: 'Ονδούρα', en: 'Honduras' },
    { gr: 'Ουγγαρία', en: 'Hungary' },
    { gr: 'Ουγκάντα', en: 'Uganda' },
    { gr: 'Ουζμπεκιστάν', en: 'Uzbekistan' },
    { gr: 'Ουκρανία', en: 'Ukraine' },
    { gr: 'Ουρουγουάη', en: 'Uruguay' },
    { gr: 'Πακιστάν', en: 'Pakistan' },
    { gr: 'Παλάου', en: 'Palau' },
    { gr: 'Παναμάς', en: 'Panama' },
    { gr: 'Παπούα Νέα Γουινέα', en: 'Papua New Guinea' },
    { gr: 'Παραγουάη', en: 'Paraguay' },
    { gr: 'Περού', en: 'Peru' },
    { gr: 'Πολωνία', en: 'Poland' },
    { gr: 'Πορτογαλία', en: 'Portugal' },
    { gr: 'Πράσινο Ακρωτήριο', en: 'Cabo Verde' },
    { gr: 'Ρουάντα', en: 'Rwanda' },
    { gr: 'Ρουμανία', en: 'Romania' },
    { gr: 'Ρωσία', en: 'Russia' },
    { gr: 'Σάο Τομέ και Πρίνσιπε', en: 'São Tomé and Príncipe' },
    { gr: 'Σαμόα', en: 'Samoa' },
    { gr: 'Σαουδική Αραβία', en: 'Saudi Arabia' },
    { gr: 'Σενεγάλη', en: 'Senegal' },
    { gr: 'Σερβία', en: 'Serbia' },
    { gr: 'Σεϋχέλλες', en: 'Seychelles' },
    { gr: 'Σιέρα Λεόνε', en: 'Sierra Leone' },
    { gr: 'Σιγκαπούρη', en: 'Singapore' },
    { gr: 'Σλοβακία', en: 'Slovakia' },
    { gr: 'Σλοβενία', en: 'Slovenia' },
    { gr: 'Σομαλία', en: 'Somalia' },
    { gr: 'Σουαζιλάνδη', en: 'Eswatini' },
    { gr: 'Σουδάν', en: 'Sudan' },
    { gr: 'Σουηδία', en: 'Sweden' },
    { gr: 'Σουρινάμ', en: 'Suriname' },
    { gr: 'Σρι Λάνκα', en: 'Sri Lanka' },
    { gr: 'Συρία', en: 'Syria' },
    { gr: 'Τανζανία', en: 'Tanzania' },
    { gr: 'Τατζικιστάν', en: 'Tajikistan' },
    { gr: 'Ταϊβάν', en: 'Taiwan' },
    { gr: 'Ταϊλάνδη', en: 'Thailand' },
    { gr: 'Τζαμάικα', en: 'Jamaica' },
    { gr: 'Τζιμπουτί', en: 'Djibouti' },
    { gr: 'Τουβαλού', en: 'Tuvalu' },
    { gr: 'Τουρκία', en: 'Türkiye' },
    { gr: 'Τουρκμενιστάν', en: 'Turkmenistan' },
    { gr: 'Τρινιντάντ και Τομπάγκο', en: 'Trinidad and Tobago' },
    { gr: 'Τσαντ', en: 'Chad' },
    { gr: 'Τσεχία', en: 'Czechia' },
    { gr: 'Τυνησία', en: 'Tunisia' },
    { gr: 'Τόγκο', en: 'Togo' },
    { gr: 'Τόνγκα', en: 'Tonga' },
    { gr: 'Υεμένη', en: 'Yemen' },
    { gr: 'Φίτζι', en: 'Fiji' },
    { gr: 'Φιλιππίνες', en: 'Philippines' },
    { gr: 'Φινλανδία', en: 'Finland' },
    { gr: 'Χιλή', en: 'Chile' },
];
